# This is a basic workflow to help you get started with Actions

name: deb_packege

on:
  push:
    branches:
     - main
    tags: 
      - "*-deb_v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: prepering to build
        run: sudo apt install cmake g++
         
      - name: Building of forrmater_lib
        run: |
         cd formatter_lib
         cmake . 
         cmake --build .
         cd ..
        
      - name: Building of forrmater_ex_lib
        run: |
          cd formatter_ex_lib
          cmake . 
          cmake --build .
          cd ..
          
      - name: Building of solver for release
        run: |
          cmake -H. -B _build -DCPACK_GENERATOR_DEB=ON
          cd _build
          make package
          make package_source
          cd ..
          cd ..
        
      - name: Moving to artifacts
        run: |
          mv _build/_CPack_Packeges/Linux/DEB/*.deb artifacts
          mv _build/_CPack_Packeges/Linux-Source/ZIP/*.zip artifacts
          mv _build/_CPack_Packeges/Linux-Source/TGZ/*.tar.gz artifacts
          
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/solver-0.1.1-Linux.deb
          asset_name: solver.deb
          asset_content_type: application/deb
          
        
          
          
